---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/gmussyco/public_html/fl-nurse
    - /bin/cp -R out/_next $DEPLOYPATH
    - /bin/cp -R out/fonts $DEPLOYPATH
    - /bin/cp -R out/images $DEPLOYPATH
    - /bin/cp out/*.* $DEPLOYPATH
